# Generated by Django 4.2.4 on 2023-08-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='comision',
        ),
        migrations.AddField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
